import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import Header from "@/src/widgets/header/ui/header";
import Footer from "@/src/widgets/footer/ui/footer";

import { cn } from "@/lib/utils";
import "./globals.css";
import { checkAuth } from "@/src/features/auth/actions";
// 1. Импортируем функцию получения категорий из базы данных
import { getAllCategories } from "@/src/lib/actions";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Legacy | Спортивная одежда для силовых тренировок",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	// Получаем статус авторизации прямо на сервере перед рендером хедера
	const isAuth = await checkAuth();

	// 🔥 ВОТ ОНО РЕШЕНИЕ: Достаем категории из PostgreSQL прямо тут на сервере!
	const categories = await getAllCategories();

	return (
		<html lang="en" className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", inter.variable)}>
			<body className="min-h-full flex flex-col">
				<Header dbCategories={categories} />
				<main className="grow">{children}</main>
				<Footer />
			</body>
		</html>
	);
}
