import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import Header from "@/src/widgets/header/ui/header";
import Footer from "@/src/widgets/footer/ui/footer";
import { cn } from "@/lib/utils";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Legacy | Спортивная одежда для силовых тренировок",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", inter.variable)}>
			<body className="min-h-full flex flex-col">
				<Header
					cartCount={0} // Сюда потом привяжешь реальное количество товаров
				/>
				<main>{children}</main>
				<Footer />
			</body>
		</html>
	);
}
